### ISSUE TITLE
Hydrus API error(?)

### ISSUE THREAD

**Issue by sbstratos79** [space-nuko/sd-webui-utilities#2]
Hydrus import script isn't working anymore. It throws this error:
`AttributeError: 'Client' object has no attribute 'add_and_tag_files'`
Hydrus v519
sd-webui-utilities commit 3545995065fc8d89847a8d8607942c9844b2c11a

**Comment by space-nuko** [comment]
Should be fixed in 975ea15ae26c0adb5fb82d6f1142f5fee15db564, could you try latest?

**Comment by sbstratos79** [comment]
It's working now. Thanks!
